# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./IDMapping.h \
    ./palette.h \
    ./version.h
SOURCES += ./IDMapping.cpp \
    ./main.cpp
